#!/usr/bin/env bash
# build-release-views.sh — regenerate a derived, disposable summary view of registry.csv.
# Not authoritative: registry.csv remains the source of truth; this file is safe to delete/regenerate.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
REGISTRY="$REPO_DIR/docs/releases/registry.csv"
VIEW="$REPO_DIR/docs/releases/registry-view.md"

if [ ! -f "$REGISTRY" ]; then
  echo "ERROR: registry not found at $REGISTRY" >&2
  exit 1
fi

{
  echo "<!-- GENERATED by scripts/release/build-release-views.sh — do not hand-edit; disposable derived view. -->"
  echo "# Release registry — summary view"
  echo
  echo "| Version | Class | Status | Branch | Approved for | Approved by | Approved at |"
  echo "|---|---|---|---|---|---|---|"
  tail -n +2 "$REGISTRY" | awk -F',' '
    function unquote(s) { gsub(/^"|"$/, "", s); return s }
    NF >= 14 {
      printf "| %s | %s | %s | %s | %s | %s | %s |\n", \
        unquote($1), unquote($2), unquote($11), unquote($4), unquote($12), unquote($13), unquote($14)
    }
  '
} > "$VIEW"

echo "Wrote $VIEW"
