// folder-index.ts — Generate per-folder summary + machine-readable CSV for graph node folders.
// Each leaf folder gets: index.csv (one row per node) + README.md (summary header + table).
// Each parent folder gets: index.csv (subfolder,count) + README.md (rollup).
// Exposed as writeFolderIndex(dir) [one folder, called by store.writeNode so it stays fresh whenever a
// node file is added] and generateFolderIndexes(nodesRoot) [full walk, used by generate-views + the
// req:folder-index CLI]. No import of store (avoids a cycle). See core.md §36.
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { GraphNode } from './schema.ts';

function trunc(s: unknown, n = 90): string {
  const t = String(s ?? '').replace(/\s+/g, ' ').trim();
  return t.length > n ? `${t.slice(0, n - 1)}…` : t;
}
function mdCell(s: unknown): string {
  return String(s ?? '').replace(/\s+/g, ' ').replace(/\|/g, '/').trim();
}
function csvCell(s: unknown): string {
  const t = String(s ?? '').replace(/\r?\n/g, ' ').trim();
  return /[",]/.test(t) ? `"${t.replace(/"/g, '""')}"` : t;
}
function tally(nodes: GraphNode[], field: keyof GraphNode): string {
  const c: Record<string, number> = {};
  for (const n of nodes) {
    const v = String((n as Record<string, unknown>)[field] ?? '—');
    c[v] = (c[v] ?? 0) + 1;
  }
  return Object.entries(c).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ${v}`).join(' · ');
}

const CSV_COLS = ['id', 'type', 'governance', 'maturity', 'delivery', 'scope', 'kind', 'statement'];

function localJson(dir: string): string[] {
  return fs.existsSync(dir) ? fs.readdirSync(dir).filter((f) => f.endsWith('.json')).sort() : [];
}
function localDirs(dir: string): string[] {
  return fs.existsSync(dir)
    ? fs.readdirSync(dir, { withFileTypes: true }).filter((e) => e.isDirectory()).map((e) => e.name).sort()
    : [];
}

/** (Re)write index.csv + README.md for a single folder, based on its current contents. Idempotent. */
export function writeFolderIndex(dir: string): void {
  if (!fs.existsSync(dir)) return;
  const files = localJson(dir);
  const dirs = localDirs(dir);
  const relName = path.basename(dir);

  if (files.length > 0) {
    // Leaf folder: per-node CSV + README with summary header + table.
    const nodes = files.map((f) => JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')) as GraphNode);
    const csv = [CSV_COLS.join(',')]
      .concat(nodes.map((n) => CSV_COLS.map((c) => csvCell((n as Record<string, unknown>)[c])).join(',')))
      .join('\n') + '\n';
    fs.writeFileSync(path.join(dir, 'index.csv'), csv);

    const md = [
      `# nodes/${relName} — ${nodes.length} node(s)`,
      '',
      '> Generated by `npm run req:folder-index` (and auto-refreshed on node writes). Do not hand-edit.',
      '> Machine-readable companion: `index.csv` in this folder.',
      '',
      '## Summary',
      `- **Total:** ${nodes.length}`,
      `- **Governance:** ${tally(nodes, 'governance')}`,
      `- **Delivery:** ${tally(nodes, 'delivery')}`,
      '',
      '## Nodes',
      '| ID | governance | scope/kind | statement |',
      '|---|---|---|---|',
      ...nodes.map((n) => {
        const tag = (n as Record<string, unknown>).scope ?? (n as Record<string, unknown>).kind ?? '—';
        return `| \`${n.id}\` | ${mdCell((n as Record<string, unknown>).governance)} | ${mdCell(tag)} | ${trunc(n.statement)} |`;
      }),
      '',
    ].join('\n');
    fs.writeFileSync(path.join(dir, 'README.md'), md);
  } else if (dirs.length > 0) {
    // Parent folder: subfolder count rollup (CSV + README).
    const counts = dirs.map((d) => [d, countJson(path.join(dir, d))] as const).filter(([, c]) => c > 0);
    const total = counts.reduce((a, [, c]) => a + c, 0);
    const csv = ['subfolder,count'].concat(counts.map(([d, c]) => `${d},${c}`)).join('\n') + '\n';
    fs.writeFileSync(path.join(dir, 'index.csv'), csv);
    const md = [
      `# nodes/${relName} — ${total} node(s) across ${counts.length} subfolder(s)`,
      '',
      '> Generated by `npm run req:folder-index`. Do not hand-edit. Companion: `index.csv`.',
      '',
      '## Summary',
      `- **Total:** ${total}`,
      '',
      '| Subfolder | Count |',
      '|---|---|',
      ...counts.sort((a, b) => b[1] - a[1]).map(([d, c]) => `| [\`${d}/\`](${d}/README.md) | ${c} |`),
      '',
    ].join('\n');
    fs.writeFileSync(path.join(dir, 'README.md'), md);
  }
}

function countJson(dir: string): number {
  let n = localJson(dir).length;
  for (const d of localDirs(dir)) n += countJson(path.join(dir, d));
  return n;
}

/** Full walk: write an index for every folder under nodesRoot. */
export function generateFolderIndexes(nodesRoot: string): number {
  let total = 0;
  function walk(dir: string): void {
    writeFolderIndex(dir);
    total += localJson(dir).length;
    for (const d of localDirs(dir)) walk(path.join(dir, d));
  }
  walk(nodesRoot);
  return total;
}

// CLI
if (import.meta.url === `file://${process.argv[1]}`) {
  const root = path.join(process.cwd(), 'docs/product/requirements/graph/nodes');
  const total = generateFolderIndexes(root);
  console.log(`folder-index: wrote README.md + index.csv per folder; ${total} nodes indexed.`);
}
